### ISSUE TITLE
Deploy policy to puppet environment

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/foreman_openscap#10]
We first need to have assignment between hosts and policies (issue #9 ).

**Comment by shlomizadok** [comment]
@isimluk -- this seems to be solved with https://github.com/OpenSCAP/foreman_openscap/pull/35.
Which issues have you encountered with that pr?

**Comment by isimluk** [comment]
Thanks Shlomi. #35 is a good start.

I believe that @ares want to make some other modifications with regards to foreman_scap_client.

Leaving open.

**Comment by isimluk** [comment]
#49 holds this. Closing
