### ISSUE TITLE
Dashboard::Manager::Mapper referenced, fails on 1.9

### ISSUE THREAD

**Issue by domcleal** [OpenSCAP/foreman_openscap#101]
Dashboard::Manager::Mapper, previously part of Foreman, is referenced here but it doesn't exist in Foreman 1.9: https://github.com/OpenSCAP/foreman_openscap/blob/v0.4.0/app/services/scaptimony/policy_dashboard/manager.rb#L29

**Comment by shlomizadok** [comment]
Will fix on master. Thanks!

**Comment by shlomizadok** [comment]
proposed fix: https://github.com/OpenSCAP/foreman_openscap/pull/103
Thanks for reporting, would love if you could review and test.

**Comment by shlomizadok** [comment]
closing as #103 is merged
