### ISSUE TITLE
The scap proxy is not ferified when not puppet (or chef) installed on the proxy

### ISSUE THREAD

**Issue by iNecas** [OpenSCAP/foreman_openscap#22]
When authorizing the smart proxy, the code used (https://github.com/OpenSCAP/foreman_openscap/blob/master/app/controllers/api/v2/openscap/arf_reports_controller.rb#L22) require the proxy to have 'Puppet' or a 'Chef Proxy' as it's features.

This means that when the scap proxy was installed as standalone, without a puppet master (or chef proxy), the calls to the Foreman would be refused.

The `foreman_abrt` plugin has the same issue.

One possible solution would be to extract the list of features to be checked into a method, and override this method from within the `ArfReportsController`

**Comment by shlomizadok** [comment]
fixed by #80 
@iNecas -- will you kindly take a look at #80 ? Thanks.
