### ISSUE TITLE
Policy definition: schedule

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/foreman_openscap#32]
Schedule of the scans/reports is property of the Policy. The schedule can be defined on the 'Compliance Policy' pages when creating new policy and when editing.

Currently user is able to define 'period' and 'weekday' by inserting a text to the form. The period and weekday properties relate to the puppet-openscap(openscap::xccdf::foreman_audit class). The UI however should be more friendly and allow drop-down selection.

Once we have issue #10 fixed, we will be in better position to defined how the schedule may look like.

**Comment by ares** [comment]
I think this should be solved by #49

**Comment by shlomizadok** [comment]
Seems to be solved by #49. @isimluk - can you please ACK?
