### ISSUE TITLE
api should take policy_id instead of policy_name

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/foreman_openscap#45]
The new foreman_scap_client sends the ID. So the foreman_proxy-openscap forwards policy_id, but scaptimony expects policy_name.

We need to merge #42 first -- otherwise there will be merge conflict.

**Comment by shlomizadok** [comment]
This actually also requires a change in Scaptimony (https://github.com/OpenSCAP/scaptimony/blob/master/lib/scaptimony/arf_reports_helper.rb#L17) -- or we can refactor this method to live in foreman_openscap

**Comment by isimluk** [comment]
I would prefer to keep it in scaptimony now, unless it is impossible.

It is not foreman specific and can be useful outside of foreman.

**Comment by shlomizadok** [comment]
Agreed. refactoring both.

**Comment by shlomizadok** [comment]
close?

**Comment by isimluk** [comment]
right.
