### ISSUE TITLE
Validation of policy attributes works only in wizard

### ISSUE THREAD

**Issue by ares** [OpenSCAP/foreman_openscap#50]
If we create a policy through wizard validations make sure that we input valid data based on current `step_index`. When we edit policy later through edit action, `step_index` is always 1 so validations like [this](https://github.com/OpenSCAP/foreman_openscap/blob/488eec978f2f6f57aa0be26c8312fd8a4b4e6fb4/app/models/concerns/foreman_openscap/policy_extensions.rb#L27) are ignored.

The issue origin is in  [`wizard_completed?` method](https://github.com/OpenSCAP/foreman_openscap/blob/488eec978f2f6f57aa0be26c8312fd8a4b4e6fb4/app/models/concerns/foreman_openscap/policy_extensions.rb#L89) which detects whether `current_step.blank?`. Current step can't be blank since it's defined as [`@current_step || steps.first`](https://github.com/OpenSCAP/foreman_openscap/blob/488eec978f2f6f57aa0be26c8312fd8a4b4e6fb4/app/models/concerns/foreman_openscap/policy_extensions.rb#L65)

**Comment by shlomizadok** [comment]
fixed by #71
