### ISSUE TITLE
as a organization user i would like to be able to upload my scap content

### ISSUE THREAD

**Issue by ohadlevy** [OpenSCAP/foreman_openscap#52]
when the scap content already exists, the error message is misleading and does not allow the user to upload its own content, even if its identical to existing content

**Comment by shlomizadok** [comment]
Seems that scap_file validation is not present anymore. Is it okay? If yes, can we close this issue? (I can create two scap_contents with the same file)

**Comment by isimluk** [comment]
yep. notabug
