### ISSUE TITLE
the actual link between a host and a policy should not be a puppet class

### ISSUE THREAD

**Issue by ohadlevy** [OpenSCAP/foreman_openscap#56]
ATM, when a policy is created, a puppet class is attached to the hostgroup.
this in turn adds the class parameters to the ENC output of a puppet run and configures the client.

this could be done automatically instead, where the enc output is appended with the scap content without a direct class / hostgroup class.

additionally, this reduces the risk of someone removing the puppet class from the hostgroup, and allow us to link the policy via any object (e.g. all hosts that belongs to org XX, domain YY, Content View etc).

**Comment by ohadlevy** [comment]
an old example at https://github.com/theforeman/foreman_content/blob/master/app/models/concerns/content/host_extensions.rb#L16

**Comment by shlomizadok** [comment]
@ohadlevy @isimluk @ares -- would love your input on: https://groups.google.com/forum/?hl=iw#!topic/foreman-dev/3Pc_k43a52k

Please advise.

**Comment by shlomizadok** [comment]
Created http://projects.theforeman.org/issues/9765 from this issue.
Closing here, let's continue discussing on http://projects.theforeman.org/issues/9765
