### ISSUE TITLE
Gemspec should list more dependencies

### ISSUE THREAD

**Issue by ares** [OpenSCAP/foreman_openscap#67]
I think we need following runtime dependencies
* scaptimony ~> ?
* rails ~> 3.2.8

**Comment by shlomizadok** [comment]
Agreed. Adding. 
foreman-1.7 on rails 3.2.21, maybe change to rails ~> 3.2.21. What says you?

**Comment by shlomizadok** [comment]
Will fix this in: #41

**Comment by ares** [comment]
right, maybe "~> 3.2.0" would be best

**Comment by shlomizadok** [comment]
@ares - actually, looking at other plugins, none require rails. Also, scaptimony is requiring rails 3.2.8
(https://github.com/OpenSCAP/scaptimony/blob/master/scaptimony.gemspec#L22 ) - so it is not needed here.

**Comment by shlomizadok** [comment]
Fixed at: https://github.com/shlomizadok/foreman_openscap/commit/02afc7ffcff1fc12aaeec99e850818c9aa42915b in PR #41

**Comment by isimluk** [comment]
Merged! Thanks!
